routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('home');

Route::get('admin/login', 'Admin\Auth\LoginController@showLoginForm')->name('admin-show-login')->middleware(['locale']);
Route::post('admin/login', 'Admin\Auth\LoginController@login')->name('admin.login');
Route::get('admin/set-locale/{locale}', 'Admin\Auth\LoginController@setLocale')->name('admin.locale');

Route::get('admin/get-client', 'Admin\OAuthClientController@index')->middleware(['cus_auth_not_redirect']); // get client ID & client secret

Route::group([
    'prefix'    => 'admin',
    'namespace' => 'Admin',
    'as'        => 'admin.',
    'middleware' => ['acl.role', 'locale']
], function () {
    Route::get('/', 'DashboardController@index')->name('dashboard');
    Route::get('/profile', 'DashboardController@profile')->name('admin-profile');
    Route::get('/logout', 'Auth\LoginController@adminLogout')->name('logout');

    /**
     * User
     */
    Route::post('/users/more', 'UserController@more')->name('users.more');
    Route::get('/users/{user}/trash', 'UserController@trash')->name('users.trash');
    Route::get('/users/{user}/restore', 'UserController@restore')->name('users.restore');
    Route::post('/users/email/existed', 'UserController@checkEmailExist')->name('users.checkEmailExist');
    Route::post('/users/trash-multi', 'UserController@trashMultiple')->name('users.trash_multi');
    Route::post('/users/delete-multi', 'UserController@deleteMultiple')->name('users.delete_multi');
    Route::post('/users/restore-multi', 'UserController@restoreMultiple')->name('users.restore_multi');
    Route::get('/users/update-profile', 'UserController@getUpdateProfile')->name('users.updateProfile');
    Route::put('/users/update-profile', 'UserController@postUpdateProfile')->name('users.updateProfile');
    Route::resource('/users', 'UserController');

    /**
     * Author
     */
    Route::get('/authors/sorting', 'AuthorController@showSorting')->name('authors.showSorting');
    Route::post('/authors/update-sorting-all', 'AuthorController@updateSortingAll')->name('authors.updateSortingAll');
    Route::get('/authors/search/{q?}', 'AuthorController@search')->name('authors.search');
    Route::resource('/authors', 'AuthorController');
    Route::post('/authors/more', 'AuthorController@more')->name('authors.more');
    Route::get('/authors/{author}/trash', 'AuthorController@trash')->name('authors.trash');
    Route::get('/authors/{author}/restore', 'AuthorController@restore')->name('authors.restore');
    Route::post('/authors/bulk-trash-multi', 'AuthorController@trashMulti')->name('authors.bulk_trash_multi');
    Route::post('/authors/restore-multi', 'AuthorController@restoreMulti')->name('authors.restore_multi');
    Route::post('/authors/delete-multi', 'AuthorController@deleteMulti')->name('authors.delete_multi');
    Route::post('/authors/update-sorting', 'AuthorController@updateSorting')->name('authors.updateSorting');

    /**
     * Salutations
     */
    Route::resource('/salutations', 'SalutationController');
    Route::post('/salutations/more', 'SalutationController@more')->name('salutations.more');

    /**
     * Media
     */
    Route::get('/media', 'ComponentController@media')->name('media.index');

    /**
     * News
     */
    Route::post('/news/ajax-related-news-pagination', 'NewsController@moreRelatedNews')->name('news.moreRelatedNews');
    Route::get('/news/search/{q?}', 'NewsController@search')->name('news.search');
    Route::resource('/news', 'NewsController');
    Route::post('/news/more', 'NewsController@more')->name('news.more');
    Route::get('/news/{news}/trash', 'NewsController@trash')->name('news.trash');
    Route::get('/news/{news}/restore', 'NewsController@restore')->name('news.restore');
    Route::post('/news/apply', 'NewsController@apply')->name('news.apply');
    Route::post('/news/bulk-trash-multi', 'NewsController@trashMulti')->name('news.bulk_trash_multi');
    Route::post('/news/restore-multi', 'NewsController@restoreMulti')->name('news.restore_multi');
    Route::post('/news/delete-multi', 'NewsController@deleteMulti')->name('news.delete_multi');

    /**
     * Categories
     */
    Route::get('/categories/sorting', 'CategoryController@showSorting')->name('categories.showSorting');
    Route::post('/categories/update-sorting', 'CategoryController@updateSorting')->name('categories.updateSorting');
    Route::resource('/categories', 'CategoryController');
    Route::post('/categories/more', 'CategoryController@more')->name('categories.more');

    /**
     * Tags
     */
    Route::resource('/tags', 'TagController');
    Route::post('/tags/more', 'TagController@more')->name('tags.more');

    /**
     * General settings
     */
    Route::get('/settings', 'GeneralSettingController@edit')->name('settings.edit');
    Route::put('/settings', 'GeneralSettingController@update')->name('settings.update');

    /**
     * Email settings
     */
    Route::get('/settings/email', 'EmailSettingController@edit')->name('settings.email.edit');
    Route::put('/settings/email', 'EmailSettingController@update')->name('settings.email.update');

    /**
     * Security
     */
    Route::get('/security', 'SecurityController@index')->name('security.read');
    Route::post('/security', 'SecurityController@update')->name('security.update');
    Route::post('/security/more', 'SecurityController@more')->name('security.more');
    Route::get('/security/unblock', 'SecurityController@unblock')->name('security.unblock');

    /**
     * App
     */
    Route::get('/app/push-notification', 'PushNotificationController@getPushNotification')->name('app.push-notification');
    Route::post('/app/push-notification', 'PushNotificationController@postPushNotification')->name('app.send.push-notification');
    Route::get('/app/settings', 'AppSettingController@edit')->name('app.settings.edit');
    Route::put('/app/settings', 'AppSettingController@update')->name('app.settings.update');
    Route::get('/app/layout/settings/{key}', 'AppLayoutController@getLayoutSettings')->name('app.layout.settings');
    Route::post('/app/layout/settings/{key}', 'AppLayoutController@saveLayoutSettings')->name('app.layout.settings.save');
    Route::any('/app/layout/setting/{key}', 'AppLayoutController@settingContent')->name('app.layout.setting');

    /**
     * Custom translation
     */
    Route::post('/translation/export', 'TranslationController@exportTranslationToJsonFile')->name('export.translation');
});

app/Models/Author.php
<?php

namespace App\Models;

use Botble\Media\Models\MediaFile;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Author extends Model
{
    use SoftDeletes;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'first_name', 'last_name', 'display_name',
        'description', 'salutation_id', 'title_id', 'image_id', 'sort_order', 'callback_url'
    ];

    /**
     * The accessors to append to the model's array form.
     *
     * @var array
     */
    protected $appends = [
        'salutation_name', 'title_name'
    ];

    /**
     * The attributes that should be visible in arrays.
     *
     * @var array
     */
    protected $visible = [
        'id', 'first_name', 'last_name', 'display_name',
        'salutation_id', 'salutation_name',
        'title_id', 'title_name', 'checkbox', 'sort_order', 'callback_url'
    ];

    /**
     * The attributes that should be mutated to dates.
     *
     * @var array
     */
    protected $dates = [ 'deleted_at' ];

    /**
     * Author's image
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasOne
     */
    public function image()
    {
        return $this
            ->hasOne(MediaFile::class, 'id', 'image_id')
            ->select(['id', 'user_id', 'name', 'folder_id', 'mime_type', 'url', 'is_public', 'deleted_at']);
    }

    /**
     * Author's salutation
     *
     * @return mixed
     */
    public function salutation()
    {
        return $this
            ->hasOne(Category::class, 'id', 'salutation_id')
            ->where('type', config('fomo.category.types.salutation'))
            ->select(['id', 'name', 'type']);
    }

    /**
     * Author's title
     *
     * @return mixed
     */
    public function title()
    {
        return $this
            ->hasOne(Category::class, 'id', 'title_id')
            ->where('type', config('fomo.category.types.title'))
            ->select(['id', 'name', 'type']);
    }

    /**
     * The news that belong to the author
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function news()
    {
        return $this->belongsToMany(News::class, 'news_authors')->withTimestamps();
    }

    /**
     * Get author's image
     */
    public function getImageSrcAttribute()
    {
        return $this->image ? url('/') . '/' . $this->image->url : '';
    }

    /**
     * Get salutation name
     *
     * @return string
     */
    public function getSalutationNameAttribute()
    {
        return $this->salutation ? $this->salutation->name : '';
    }

    /**
     * Get title name
     *
     * @return string
     */
    public function getTitleNameAttribute()
    {
        return $this->title ? $this->title->name : '';
    }

    /**
     * Get display name
     *
     * @param string $value
     *
     * @return string
     * @ticket #13385 - HFBACKEND-91 News / Edit - Show Authors Display name in Selectbox
     */
    public function getDisplayNameAttribute($value)
    {
        // handle for old data which display name has value is null
        $name = empty($value) ? sprintf('%s %s', $this->first_name, $this->last_name) : $value;

        return $name;
    }
}

resources/views/admin/author/create.blade.php
@extends(config('metronic.layout.root'))

@section('title', __('Create new author'))

@section('content')
    @include('admin.author.form', [
        'title'         => __('Create new author'),
        'route'         => route('admin.authors.store'),
        'btnSubmitText' => __('Create'),
    ])
@endsection

resources/views/admin/author/edit.blade.php
@extends(config('metronic.layout.root'))

@section('title', __('Authors Edit'))

@section('action_buttons')
    <div class="clearfix">
        <div class="btn-group pull-right">
            <a href="{{ route('admin.authors.show', [ 'author' => $author->id ]) }}" class="btn btn-default">{{ __('Show detail') }}</a>

            <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                <i class="fa fa-angle-down"></i>
            </button>

            <ul class="dropdown-menu pull-left" role="menu">
                <li>
                    <a href="{{ route('admin.authors.trash', [ 'author' => $author->id ]) }}">{{ __('Trash') }}</a>
                </li>
            </ul>
        </div>
    </div>
@endsection

@section('content')
    @include('admin.author.form', [
        'title'         => __('Edit author'),
        'route'         => route('admin.authors.update', ['author' => $author->id]),
        'btnSubmitText' => __('Save Changes'),
    ])
@endsection

resources/views/admin/author/form.blade.php
<div class="row">
    <div class="col-md-12">
        <div class="profile-content">
            <div class="row">
                <form role="form" action="{{ empty($route) ? '' : $route }}" method="POST" class="form-horizontal form-validation submit-frm" enctype="multipart/form-data">
                <div class="col-md-9">
                    <div class="portlet light bordered no-padding-bottom">
                        <div class="portlet-title">
                            <div class="caption font-green">{{ empty($title) ? __('Form Author') : $title }}</div>
                            @include('admin.components.portlet-tools')
                            <div class="actions">
                                @include('admin.components.full-screen')
                            </div>
                        </div>

                        <div class="portlet-body form">
                                {{ csrf_field() }}

                                @if ( isset($author) )
                                    {{ method_field('PUT') }}
                                @endif

                                <div class="form-body">
                                    <div class="form-group {{ $errors->has('salutation_id') ? 'has-error' : '' }}">
                                        <label class="col-md-2 control-label label-required" for="salutation_id">{{ __('Salutation') }}</label>
                                        <div class="col-md-10">
                                            <select class="form-control" name="salutation_id" id="salutation_id" required>
                                                <option value="" selected disabled>{{ __('Please choose') }}</option>
                                                @foreach($salutations as $key => $salutation)
                                                    <option @if ( isset($author) && $author->salutation_id == $key ) selected @endif value="{{ $key }}">{{ $salutation }}</option>
                                                @endforeach
                                            </select>
                                            <div class="form-control-focus"></div>
                                            <span class="help-block">{{ $errors->first('salutation_id') }}</span>
                                        </div>
                                    </div>

                                    <div class="form-group {{ $errors->has('title_id') ? 'has-error' : '' }}">
                                        <label class="col-md-2 control-label" for="title_id">{{ __('Title') }}</label>
                                        <div class="col-md-10">
                                            <select class="form-control" name="title_id" id="title_id">
                                                <option value="">{{ __('Please choose') }}</option>
                                                @foreach($titles as $key => $title)
                                                    <option @if ( isset($author) && $author->title_id == $key ) selected @endif value="{{ $key }}">{{ $title }}</option>
                                                @endforeach
                                            </select>
                                            <div class="form-control-focus"></div>
                                            <span class="help-block">{{ $errors->first('title_id') }}</span>
                                        </div>
                                    </div>

                                    <div class="form-group  {{ $errors->has('first_name') ? 'has-error' : '' }}">
                                        <label class="col-md-2 control-label label-required" for="first_name">{{ __('First name') }}</label>
                                        <div class="col-md-10">
                                            <input type="text"
                                                   id="first_name"
                                                   name="first_name"
                                                   class="form-control"
                                                   value="{{ old('first_name', isset($author->first_name) ? $author->first_name : '') }}"
                                                   required>
                                            <div class="form-control-focus"></div>
                                            <span class="help-block">{{ $errors->first('first_name') }}</span>
                                        </div>
                                    </div>

                                    <div class="form-group  {{ $errors->has('last_name') ? 'has-error' : '' }}">
                                        <label class="col-md-2 control-label label-required" for="last_name">{{ __('Last name') }}</label>
                                        <div class="col-md-10">
                                            <input type="text"
                                                   id="last_name"
                                                   name="last_name"
                                                   class="form-control"
                                                   value="{{ old('last_name', isset($author->last_name) ? $author->last_name : '') }}"
                                                   required>
                                            <div class="form-control-focus"></div>
                                            <span class="help-block">{{ $errors->first('last_name') }}</span>
                                        </div>
                                    </div>

                                    <div class="form-group  {{ $errors->has('display_name') ? 'has-error' : '' }}">
                                        <label class="col-md-2 control-label label-required" for="display_name">{{ __('Display name') }}</label>
                                        <div class="col-md-10">
                                            <input type="text"
                                                   id="display_name"
                                                   name="display_name"
                                                   class="form-control"
                                                   value="{{ old('display_name', isset($author->display_name) ? $author->display_name : '') }}"
                                                   required>
                                            <div class="form-control-focus"></div>
                                            <span class="help-block">{{ $errors->first('display_name') }}</span>
                                        </div>
                                    </div>

                                    <div class="form-group  {{ $errors->has('callback_url') ? 'has-error' : '' }}">
                                        <label class="col-md-2 control-label " for="callback_url">{{ __('Callback URL') }}</label>
                                        <div class="col-md-10">
                                            <input type="text"
                                                   id="callback_url"
                                                   name="callback_url"
                                                   class="form-control"
                                                   value="{{ old('callback_url', isset($author->callback_url) ? $author->callback_url : '') }}"
                                                   >
                                            <div class="form-control-focus"></div>
                                            <span class="help-block">{{ $errors->first('callback_url') }}</span>
                                        </div>
                                    </div>

                                    <div class="form-group  {{ $errors->has('description') ? 'has-error' : '' }}">
                                        <label class="col-md-2 control-label" for="description">{{ __('Description') }}</label>
                                        <div class="col-md-10">
                                            @include('admin.components.addMedia')
                                            <textarea name="description"
                                                      id="description"
                                                      class="summernote form-control"
                                                      data-editor="summernote"
                                                      rows="15">{{ old('description', isset($author->description) ? $author->description : '') }}</textarea>
                                            <span class="help-block">{{ $errors->first('description') }}</span>
                                        </div>
                                    </div>
                                </div>
                        </div>
                    </div>
                </div>

                <div class="col-md-3">
                    @include('admin.components.image-box', ['title' => __('Primary image'), 'data' => isset($author) ? $author : ''])
                </div>
                </form>
            </div>
        </div>
    </div>
</div>

@push('footer')
    @include('media::partials.media')
@endpush

resources/views/admin/author/show.blade.php
@extends(config('metronic.layout.root'))

@section('title', __('Authors Detail'))

@section('action_buttons')
    <div class="clearfix">
        <div class="btn-group pull-right">
            <a href="{{ route('admin.authors.edit', [ 'author' => $author->id ]) }}" class="btn btn-default">{{ __('Edit') }}</a>

            <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                <i class="fa fa-angle-down"></i>
            </button>

            <ul class="dropdown-menu pull-left" role="menu">
                <li>
                    <a href="{{ route('admin.authors.trash', [ 'author' => $author->id ]) }}">{{ __('Trash') }}</a>
                </li>
            </ul>
        </div>
    </div>
@endsection

@section('content')
<div class="row">
    <div class="col-md-12">
        <div class="profile-content">
            <div class="row">
                <div class="col-md-10">
                    <div class="portlet light bordered no-padding-bottom">
                        <div class="portlet-title">
                            <div class="caption font-green">{{ __('Personal data') }}</div>
                            <div class="actions">
                                <button class="btn btn-icon-only btn-default fullscreen" data-original-title="Vollbild" title="{{ __('Full screen') }}"></button>
                            </div>
                        </div>

                        <div class="portlet-body form">
                            <table class="table fomo-show-author-tbl">
                                <tbody>
                                    <tr>
                                        <th width="130">{{ __('Salutation') }}</th>
                                        <td>{{ $author->salutation_name }}</td>
                                    </tr>
                                    <tr>
                                        <th width="130">{{ __('Title') }}</th>
                                        <td>{{ $author->title_name }}</td>
                                    </tr>
                                    <tr>
                                        <th width="130">{{ __('First name') }}</th>
                                        <td>{{ $author->first_name }}</td>
                                    </tr>
                                    <tr>
                                        <th width="130">{{ __('Last name') }}</th>
                                        <td>{{ $author->last_name }}</td>
                                    </tr>
                                    <tr>
                                        <th width="130">{{ __('Display name') }}</th>
                                        <td>{{ $author->display_name }}</td>
                                    </tr>
                                    <tr>
                                        <th width="130">{{ __('Callback URL') }}</th>
                                        <td><a href="{{ $author->callback_url }}" target="_blank">{{ $author->callback_url }}</a></td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>

                    <div class="portlet light bordered no-padding-bottom">
                        <div class="portlet-title">
                            <div class="caption font-green">{{ __('Description') }}</div>
                            <div class="actions">
                                @include('admin.components.full-screen')
                            </div>
                        </div>

                        <div class="portlet-body form">
                            {!! $author->description !!}
                        </div>
                    </div>
                </div>

                <div class="col-md-2">
                    <div class="portlet light bordered no-padding-bottom">
                        <div class="portlet-title">
                            <div class="caption font-green">{{ __('Primary Image') }}</div>
                        </div>

                        <div class="portlet-body form">
                            <div id="crop-avatar">
                                @if ($author->image_src)
                                    <div class="form-body">
                                        <div class="form-group">
                                            <!-- CURRENT AVATAR -->
                                            <div class="avatar-view">
                                                <img class="img-responsive" src="{{ $author->image_src }}" alt="{{ __('Image') }}">
                                            </div>
                                        </div>
                                    </div>
                                @else
                                    {{ __("Not available") }}
                                @endif
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/author/sorting.blade.php
@extends(config('metronic.layout.root'))

@section('title', __('Authors Sorting'))
@section('main_title', __('Authors'))

@section('action_buttons')
    <div class="clearfix">
        <div class="btn-group pull-right">
            <a href="{{ route('admin.authors.showSorting') }}" class="btn btn-default">{{ __('Edit') }}</a>

            <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                <i class="fa fa-angle-down"></i>
            </button>

        </div>
    </div>
@endsection

@section('content')
<div class="row">
    <div class="col-md-12">
        <div class="profile-content">
            <div class="row">
                <div class="col-md-12">
                    <div class="portlet light bordered no-padding-bottom">
                        <div class="portlet-title">
                            <div class="caption font-green">{{ __('Sorting Authors') }}</div>
                            <div class="actions">
                                <button class="btn btn-icon-only btn-default fullscreen" data-original-title="Vollbild" title="{{ __('Full screen') }}"></button>
                            </div>
                        </div>

                        <div class="portlet-body form">
                            <form action="{{ route('admin.authors.updateSortingAll') }}" method="POST" id="fomo-update-sorting">
                                {{ csrf_field() }}
                                <div class="dd nestable">
                                    <ol class="dd-list">
                                        <li class="item-heading">
                                            <div class="dd-heading">
                                                <div class="tb-fomo-nestable">
                                                    <div class="st-col-left st-col st-col-0">
                                                        @php echo __('Salutation') @endphp
                                                    </div>
                                                    <div class="st-col-left st-col st-col-1">
                                                        @php echo __('Title') @endphp
                                                    </div>
                                                    <div class="st-col-left st-col st-col-2">
                                                        @php echo __('First name') @endphp
                                                    </div>
                                                    <div class="st-col-left st-col st-col-3">
                                                        @php echo __('Last name') @endphp
                                                    </div>
                                                </div>
                                            </div>
                                        </li>
                                        @if (!empty($authors))
                                            @foreach($authors as $key => $author)
                                                <li class="dd-item" data-id="@php echo $author->id @endphp">
                                                    <div class="dd-handle">
                                                        <div class="tb-fomo-nestable">
                                                            <div class="st-col-left st-col st-col-0">
                                                                @php echo ($author->salutation) ? $author->salutation->name : '' @endphp
                                                            </div>
                                                            <div class="st-col-left st-col st-col-1">
                                                                @php echo ($author->title) ? $author->title->name : '' @endphp
                                                            </div>
                                                            <div class="st-col-left st-col st-col-2">@php echo $author->first_name @endphp</div>
                                                            <div class="st-col-left st-col st-col-3">@php echo $author->last_name @endphp</div>
                                                        </div>
                                                    </div>
                                                </li>
                                            @endforeach
                                        @endif
                                    </ol>
                                </div>
                                <div class="modal-footer">
                                    <button type="submit" id="authors-sorting-full" class="btn btn-default green pull-right">{{ __('Update') }}</button>
                                </div>
                                <div class="spinner-loading font-green text-center" style="display: none"><i class="fa fa-spinner fa-spin fa-3x"></i></div>
                                <input type="hidden" name="myData" id="myData"/>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection
@push('styles')
<link href="{{ asset('/vendor/metronic/global/plugins/jquery-nestable/jquery.nestable.css') }}" rel="stylesheet" type="text/css" />
@endpush
@push('scripts')
<script src="{{ asset('/vendor/metronic/global/plugins/jquery-nestable/jquery.nestable.js') }}" type="text/javascript"></script>
@endpush